# Generated by Django 5.0.2 on 2024-02-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_userrecord_inventory_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
